sudo: required

service: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec 'RAILS_ENV=test' web rails db:create
  - docker-compose exec 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec 'RAILS_ENV=test' web rails test